name: Tibia Scanner

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

concurrency:
  group: tibia-scanner
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Tibia scanner
        run: npm run scanner
        env:
          TIBIA_SCANNER_WEBHOOK_URL: ${{ secrets.TIBIA_SCANNER_WEBHOOK_URL }}
          ERROR_WEBHOOK_URL: ${{ secrets.ERROR_WEBHOOK_URL }}
          SEND_TO_DISCORD: "true"

      - name: Commit state
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add state.json
          git commit -m "update tibia scanner state" || echo "No state changes"

          git pull --rebase
          git push
